apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cykube-build-{{ testrun_id }}
  namespace: cykube
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "10G"
---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    branch: {{ branch }}
    type: cykube-builder
    testrun_id: "{{ testrun_id }}"
  name: cykube-build-{{ testrun_id }}
  namespace: cykube
spec:
  backoffLimit: 1
  ttlSecondsAfterFinished: 3600
  template:
    spec:
      volumes:
        - name: build
          persistentVolumeClaim:
            claimName: cykube-build-{{ testrun_id }}
      containers:
      - name: build
        image: {{ image }}
        args: [ "build", "{{ testrun_id }}" ]
        imagePullPolicy: IfNotPresent
        env:
          - name: BUILD_DIR
            value: "/usr/app/dist"
          - name: CACHE_URL
            value: "http://cache"
          - name: API_TOKEN
            value: {{ token }}
          - name: AGENT_URL
            value: "http://cykube:5000"
          - name: MAIN_API_URL
            value: {{ main_api_url }}
        resources:
          requests:
            cpu: {{ cpu }}
            memory: {{ memory }}
        volumeMounts:
          - mountPath: /usr/app/dist
            name: build
      restartPolicy: Never


