cacheStorage: 10G
namespace: cykube
agentName: "default"
tag: "c024906"
apiUrl: "https://app.cykube.net/api"
agentUrl: "http://cykube-agent:5000"
cacheUrl: "http://cykube-cache"
token: "dummy"
sentryDsn: "https://aa340c820e424f4bafddd9b378b18493@o4504740483432448.ingest.sentry.io/4504740484743168"
gcpServiceAccount: null
platform: null
