apiUrl: "https://api.cykubed.com"
replicas: 2
token: ""
sentryDsn: "https://58704c4839d449d587d9f236564ca579@o4505122332803072.ingest.sentry.io/4505122348466176"
imagePullPolicy: Always
cache:
  size: "10Gi"
gcpServiceAccount: ""
storageClass: ""
platform: "minikube"
architecture: "replicated"
validPlatforms:
  - GKE
  - AKS
  - minikube
  - EKS
  - generic
volumeSnapshotClassPlatforms:
  - AKS
  - GKE
  - minikube
redis:
  sentinel:
    enabled: true
    resources:
      requests:
        cpu: "100m"
        memory: "100Mi"
      limits:
        cpu: "100m"
        memory: "100Mi"
  master:
    resources:
      requests:
        cpu: "100m"
        memory: "100Mi"
      limits:
        cpu: "100m"
        memory: "100Mi"
  replica:
    resources:
      requests:
        cpu: "100m"
        memory: "100Mi"
      limits:
        cpu: "100m"
        memory: "100Mi"


