steps:
 - name: 'gcr.io/cloud-builders/git'
   script: |
     git config -f .gitmodules submodule.src/common.url https://source.developers.google.com/p/cykubed/r/github_cykubed_cykubed-common
     git submodule init
     git submodule update

 - name: gcr.io/kaniko-project/executor:latest
   args: [ "--dockerfile=Dockerfile",
           "--destination=us-docker.pkg.dev/cykubed/public/agent:1.39.0",
           "--cache=true"]

 - name: 'gcr.io/cykubed/helm:3.7.0'
   id: 'Build chart'
   script: |
      helm package ./chart -d ./dist --app-version "1.39.0" --version "1.39.0"
      helm repo index ./dist --url https://charts.cykubed.com

 - name: 'gcr.io/cloud-builders/npm'
   id: 'Publish chart'
   script: |
       npm i -g wrangler
       wrangler r2 object put charts/index.yaml --file=./dist/index.yaml 
       wrangler r2 object put "charts/agent-1.39.0.tgz" --file=./dist/agent-1.39.0.tgz
   secretEnv: ['CLOUDFLARE_API_TOKEN', 'CLOUDFLARE_ACCOUNT_ID']

 - name: alpine/httpie
   id: Set current version number
   script: |
       http POST "https://api.cykubed.com/admin/image/agent/current-version/1.39.0" -A bearer -a $CYKUBED_API_TOKEN
   secretEnv: ['CYKUBED_API_TOKEN']

 - name: gcr.io/cloud-builders/curl
   id: Notify Slack
   secretEnv: ['SLACK_HOOK_URL']
   script: |
      echo "{\"text\":\"Cykubed agent published created with tag 1.39.0\"}" > payload.json
      /usr/bin/curl -X POST -H 'Content-type: application/json' --data "@payload.json" $SLACK_HOOK_URL

availableSecrets:
  secretManager:
    - versionName: projects/1029845047729/secrets/CYKUBED_API_TOKEN/versions/1
      env: 'CYKUBED_API_TOKEN'
    - versionName: projects/1029845047729/secrets/cloudflare_api_token/versions/3
      env: 'CLOUDFLARE_API_TOKEN'
    - versionName: projects/1029845047729/secrets/cloudflare_account_id/versions/1
      env: 'CLOUDFLARE_ACCOUNT_ID'
    - versionName: projects/1029845047729/secrets/SLACK_HOOK_URL/versions/1
      env: 'SLACK_HOOK_URL'

