steps:
 - name: 'gcr.io/cloud-builders/git'
   entrypoint: 'bash'
   args:
   - '-c'
   - |
     git config -f .gitmodules submodule.src/common.url https://source.developers.google.com/p/iron-lodge-372417/r/github_cykube_cykube-common
     git submodule init
     git submodule update

 - name: 'gcr.io/cloud-builders/docker'
   entrypoint: 'bash'
   args: ['-c', 'docker login --username=nickbrookck --password=$$PASSWORD']
   secretEnv: ['PASSWORD']

 - name: alpine/httpie
   id: Get next version number
   entrypoint: sh
   args:
     - '-c'
     - |-
       http https://api.cykube.net/admin/image/agent/next-version/minor -A bearer -a $$CYKUBE_API_TOKEN -b > /workspace/version.txt
   secretEnv: ['CYKUBE_API_TOKEN']

 - name: 'gcr.io/cloud-builders/docker'
   entrypoint: 'bash'
   id: 'Build image'
   args:
     - '-c'
     - |-       
       docker build -t nickbrookck/cykube-agent:$(cat /workspace/version.txt) .

 - name: 'gcr.io/cloud-builders/docker'
   entrypoint: 'bash'
   id: 'Push image'
   args:
     - '-c'
     - |-       
       docker push nickbrookck/cykube-agent:$(cat /workspace/version.txt) .

 - name: 'bash'
   args: ['./scripts/publish-chart.sh']

 - name: alpine/httpie
   id: Set current version number
   entrypoint: sh
   args:
     - '-c'
     - |-
       http POST https://api.cykube.net/admin/image/agent/current-version/$(cat /workspace/version.txt) -A bearer -a $$CYKUBE_API_TOKEN
   secretEnv: ['CYKUBE_API_TOKEN']

# - name: gcr.io/cloud-builders/kubectl
#   id: Deploy
#   entrypoint: /bin/sh
#   args:
#      - '-c'
#      - |
#        set -x && \
#        gcloud container clusters get-credentials cykube --region europe-west2 --project iron-lodge-372417 && \
#        kubectl set image -n cykube deployment/cykube-agent server=nickbrookck/cykube-agent:$SHORT_SHA && \
#        kubectl set image -n cykube statefulset/fs fs=nickbrookck/cykube-agent:$SHORT_SHA && \
#        kubectl rollout status -n cykube deployment/cykube-agent
#        kubectl rollout status -n cykube statefulset/fs

 - name: gcr.io/cloud-builders/curl
   id: Notify
   entrypoint: 'bash'
   args:
     - '-c'
     - |-
       curl -X POST -H 'Content-type: application/json' --data '{"text":"Cykube agent $(cat /workspace/version.txt) ($SHORT_SHA) published"}' https://hooks.slack.com/services/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

availableSecrets:
  secretManager:
    - versionName: projects/1090211518452/secrets/cykube-api-token/versions/4
      env: 'CYKUBE_API_TOKEN'
    - versionName: projects/1090211518452/secrets/docker-hub-password/versions/1
      env: 'PASSWORD'
