steps:
 - name: 'gcr.io/cloud-builders/git'
   entrypoint: 'bash'
   args:
   - '-c'
   - |
     git config -f .gitmodules submodule.src/common.url https://source.developers.google.com/p/cykubeapp/r/github_cykube_cykube-common
     git submodule init
     git submodule update

 - name: alpine/httpie
   id: Get next version number
   entrypoint: sh
   args:
     - '-c'
     - |-
       http GET https://api.cykube.net/admin/image/agent/next-version/minor -A bearer -a $$CYKUBE_API_TOKEN -b > /workspace/version.txt && echo "$(cat /workspace/version.txt)"
   secretEnv: ['CYKUBE_API_TOKEN']

 - name: 'gcr.io/cloud-builders/docker'
   entrypoint: 'bash'
   id: 'Build image'
   args:
     - '-c'
     - |-       
       echo "Building europe-west2-docker.pkg.dev/cykubeapp/cykube/agent:$(cat /workspace/version.txt)" && 
       docker build -t "europe-west2-docker.pkg.dev/cykubeapp/cykube/agent:$(cat /workspace/version.txt)" .

 - name: 'gcr.io/cloud-builders/docker'
   id: 'Push image'
   entrypoint: 'bash'
   args:
     - '-c'
     - |-       
       docker push "europe-west2-docker.pkg.dev/cykubeapp/cykube/agent:$(cat /workspace/version.txt)" 

 - name: 'gcr.io/$PROJECT_ID/helm:3.7.0'
   entrypoint: 'bash'
   id: 'Build chart'
   args:
     - '-c'
     - |-                     
       sh ./scripts/cloudbuild/build-chart.sh

 - name: 'gcr.io/cloud-builders/npm'
   entrypoint: 'bash'
   id: 'Publish chart'
   args:
     - '-c'
     - |-
       wrangler r2 object put charts/index.yaml --file=/workspace/build/dist/index.yaml && 
       wrangler r2 object put "charts/agent-$(cat /workspace/version.txt).tgz" --file="/workspace/build/dist/agent-$(cat /workspace/version.txt)".tgz
   secretEnv: ['CLOUDFLARE_API_TOKEN', 'CLOUDFLARE_ACCOUNT_ID']

 - name: alpine/httpie
   id: Set current version number
   entrypoint: sh
   args:
     - '-c'
     - |-
       http POST "https://api.cykube.net/admin/image/agent/current-version/$(cat /workspace/version.txt)" -A bearer -a $$CYKUBE_API_TOKEN
   secretEnv: ['CYKUBE_API_TOKEN']

# - name: gcr.io/cloud-builders/kubectl
#   id: Deploy
#   entrypoint: /bin/sh
#   args:
#      - '-c'
#      - |
#        set -x && \
#        gcloud container clusters get-credentials cykube --region europe-west2 --project iron-lodge-372417 && \
#        kubectl set image -n cykube deployment/cykube-agent server=nickbrookck/cykube-agent:$SHORT_SHA && \
#        kubectl set image -n cykube statefulset/fs fs=nickbrookck/cykube-agent:$SHORT_SHA && \
#        kubectl rollout status -n cykube deployment/cykube-agent
#        kubectl rollout status -n cykube statefulset/fs

 - name: gcr.io/cloud-builders/curl
   id: Notify
   entrypoint: 'bash'
   args:
     - '-c'
     - |-
       curl -X POST -H 'Content-type: application/json' --data '{"text":"Cykube agent $(cat /workspace/version.txt) ($SHORT_SHA) published"}' https://hooks.slack.com/services/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

availableSecrets:
  secretManager:
    - versionName: projects/489847359241/secrets/cykube-api-token/versions/1
      env: 'CYKUBE_API_TOKEN'
    - versionName: projects/489847359241/secrets/cloudflare_api_token/versions/1
      env: 'CLOUDFLARE_API_TOKEN'
    - versionName: projects/489847359241/secrets/cloudflare_account_id/versions/1
      env: 'CLOUDFLARE_ACCOUNT_ID'

