steps:
 - name: 'gcr.io/cloud-builders/git'
   entrypoint: 'bash'
   args:
   - '-c'
   - |
     git config -f .gitmodules submodule.src/common.url https://source.developers.google.com/p/cykubeapp/r/github_cykube_cykube-common
     git submodule init
     git submodule update

 - name: alpine/httpie
   id: Get next version number
   entrypoint: sh
   args:
     - '-c'
     - |-
       http GET https://api.cykubed.com/admin/image/agent/next-version/minor -A bearer -a $$CYKUBE_API_TOKEN -b > /workspace/version.txt && echo "$(cat /workspace/version.txt)"
   secretEnv: ['CYKUBE_API_TOKEN']

 - name: 'gcr.io/cloud-builders/docker'
   args: [ 'pull',  'europe-docker.pkg.dev/cykubeapp/cykubed/agent:latest']

 - name: 'gcr.io/cloud-builders/docker'
   entrypoint: 'bash'
   id: 'Build image'
   args:
     - '-c'
     - |-       
       echo "Building agent:$(cat /workspace/version.txt)" && 
       docker build -t "europe-docker.pkg.dev/cykubeapp/cykubed/agent:$(cat /workspace/version.txt)"  -t "europe-docker.pkg.dev/cykubeapp/cykubed/agent:$SHORT_SHA" -t "europe-docker.pkg.dev/cykubeapp/cykubed/agent:latest" --cache-from="europe-docker.pkg.dev/cykubeapp/cykubed/agent:latest" .

 - name: 'gcr.io/cloud-builders/docker'
   id: 'Push image'
   entrypoint: 'bash'
   args:
     - '-c'
     - |-       
       docker push -a europe-docker.pkg.dev/cykubeapp/cykubed/agent 

 - name: 'gcr.io/$PROJECT_ID/helm:3.7.0'
   entrypoint: 'bash'
   id: 'Build chart'
   args:
     - '-c'
     - |-                     
       sh ./scripts/cloudbuild/build-chart.sh

 - name: 'gcr.io/cloud-builders/npm'
   entrypoint: 'bash'
   id: 'Publish chart'
   args:
     - '-c'
     - |-
       npm i -g wrangler &&
       wrangler r2 object put charts/index.yaml --file=/workspace/build/dist/index.yaml && 
       wrangler r2 object put "charts/agent-$(cat /workspace/version.txt).tgz" --file="/workspace/build/dist/agent-$(cat /workspace/version.txt)".tgz
   secretEnv: ['CLOUDFLARE_API_TOKEN', 'CLOUDFLARE_ACCOUNT_ID']

 - name: alpine/httpie
   id: Set current version number
   entrypoint: sh
   args:
     - '-c'
     - |-
       http POST "https://api.cykubed.com/admin/image/agent/current-version/$(cat /workspace/version.txt)" -A bearer -a $$CYKUBE_API_TOKEN
   secretEnv: ['CYKUBE_API_TOKEN']

 - name: alpine/httpie
   id: Notify
   entrypoint: sh
   args:
     - '-c'
     - |-
       http POST https://hooks.slack.com/services/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 < /workspace/notify.json

availableSecrets:
  secretManager:
    - versionName: projects/489847359241/secrets/cykube-api-token/versions/7
      env: 'CYKUBE_API_TOKEN'
    - versionName: projects/489847359241/secrets/cloudflare_api_token/versions/2
      env: 'CLOUDFLARE_API_TOKEN'
    - versionName: projects/489847359241/secrets/cloudflare_account_id/versions/1
      env: 'CLOUDFLARE_ACCOUNT_ID'

