steps:
 - name: 'gcr.io/cloud-builders/git'
   entrypoint: 'bash'
   args:
   - '-c'
   - |
     git config -f .gitmodules submodule.src/common.url https://source.developers.google.com/p/iron-lodge-372417/r/github_cykube_cykube-common
     git submodule init
     git submodule update

 - name: 'gcr.io/cloud-builders/docker'
   entrypoint: 'bash'
   args: ['-c', 'docker login --username=nickbrookck --password=$$PASSWORD']
   secretEnv: ['PASSWORD']

 - name: 'gcr.io/cloud-builders/docker'
   entrypoint: 'bash'
   args: ['-c', 'docker build -t nickbrookck/cykube-agent:$SHORT_SHA .']

 - name: 'gcr.io/cloud-builders/docker'
   entrypoint: 'bash'
   args: ['-c', 'docker push nickbrookck/cykube-agent:$SHORT_SHA']

 - name: gcr.io/cloud-builders/kubectl
   id: Deploy
   entrypoint: /bin/sh
   args:
      - '-c'
      - |
        set -x && \
        gcloud container clusters get-credentials cykube --region europe-west2 --project iron-lodge-372417 && \
        kubectl set image -n cykube deployment/cykube-agent server=nickbrookck/cykube-agent:$SHORT_SHA && \
        kubectl set image -n cykube statefulset/fs fs=nickbrookck/cykube-agent:$SHORT_SHA && \
        kubectl rollout status -n cykube deployment/cykube-agent
        kubectl rollout status -n cykube statefulset/fs

 - name: gcr.io/cloud-builders/curl
   id: Notify
   args: ['-X', 'POST', '-H', 'Content-type: application/json', '--data', '{"text":"Cykube Agent $SHORT_SHA redeployed"}', 'https://hooks.slack.com/services/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']

availableSecrets:
  secretManager:
    - versionName: projects/1090211518452/secrets/docker-hub-password/versions/1
      env: 'PASSWORD'
