version: "3.2"

services:
  redis:
    image: redis
  mysql:
    image: mysql:5.7
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: "testhub"
      MYSQL_ROOT_PASSWORD: "fishfish1234"
    volumes:
      - ../docker-data/cypress-hub-mysql:/var/lib/mysql
      - ./docker/mysql.cnf:/etc/mysql/conf.d/custom.cnf
    ports:
      - 33062:3306
  hub:
    image: gcr.io/kisanhub-uat/test-hub:latest
    restart: always
    environment:
      CYPRESSHUB_DATABASE_URL: mysql+mysqldb://root:fishfish1234@mysql/testhub
      REDIS_HOST: redis
    env_file:
      - testhub.env
    ports:
      - 8004:80
    volumes:
    - ./src:/app/app
  worker:
    image: gcr.io/kisanhub-uat/test-hub:latest
    command: celery -A tasks worker
    restart: always
    environment:
      CYPRESSHUB_DATABASE_URL: mysql+mysqldb://root:fishfish1234@mysql/testhub
      REDIS_HOST: redis
    env_file:
      - testhub.env
    volumes:
    - ./src:/app/app





