[tool.poetry]
name = "cykube-hub"
version = "0.1.0"
description = ""
authors = ["nick <nickbrook72@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
six = "*"
kubernetes = "*"
uvicorn = {extras = ["standard"], version = "*"}
aiohttp = {extras = ["speedups"], version = "*"}
fastapi = "^0.87"
fastapi-utils = "*"
loguru = "*"
ecdsa = "*"
jwt = "*"
websockets = "*"
python-multipart = "*"
fastapi-exceptions = "^0.1.0"
httpx = "^0.23.1"
cachetools = "^5.2.0"
python-dateutil = "^2.8.2"
motor = "^3.1.1"
pymongo = "^4.3.3"
aiofiles = "^23.1.0"
sentry-sdk = {extras = ["httpx"], version = "^1.15.0"}
google-cloud-logging = "^3.5.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.2.0"
python-jose = "*"
respx = "^0.20.1"
ipython = "^8.8.0"
pytest-mock = "^3.10.0"
mongomock-motor = "^0.0.17"
pytest-asyncio = "^0.20.3"
pydantic-factories = "^1.17.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
