[tool.poetry]
name = "cykube-hub"
version = "0.1.0"
description = ""
authors = ["nick <nickbrook72@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
google-cloud-storage = "*"
python-jose = "*"
six = "*"
google-cloud-logging = "*"
google-cloud-container = "*"
kubernetes = "*"
uvicorn = {extras = ["standard"], version = "*"}
aiohttp = {extras = ["speedups"], version = "*"}
fastapi = "^0.87"
fastapi-utils = "*"
loguru = "*"
click = "*"
pydantic-to-typescript = "*"
ecdsa = "*"
jwt = "*"
websockets = "*"
python-multipart = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
