[tool.poetry]
name = "cykube-agent"
version = "0.1.0"
description = ""
authors = ["nick <nick@cykube.net>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
kubernetes = "*"
loguru = "*"
websockets = "*"
httpx = "^0.23.1"
cachetools = "^5.2.0"
python-dateutil = "^2.8.2"
motor = "^3.1.1"
pymongo = "^4.3.3"
sentry-sdk = {extras = ["httpx"], version = "^1.15.0"}

[tool.poetry.group.dev.dependencies]
pytest = "^7.2.0"
python-jose = "*"
ipython = "^8.8.0"
pytest-mock = "^3.10.0"
mongomock-motor = "^0.0.17"
pytest-asyncio = "^0.20.3"
pydantic-factories = "^1.17.2"
mongomock = "^4.1.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
