apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: agent
  labels:
    app: agent
spec:
  ports:
  - port: 8100
    name: agent
  clusterIP: None
  selector:
    app: server

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: agent-nginx-conf
  namespace: {{ .Values.namespace }}
data:
  nginx.conf: |
    user nginx;
    worker_processes  1;
    events {
      worker_connections  10240;
    }
    http {
      server {
          listen       8100;
          server_name  localhost;

          location /fs {
            root /cache;
            client_max_body_size 1000M;
          }

          location / {
             proxy_pass http://localhost:8101/;
             proxy_http_version 1.1;
             proxy_set_header Host $host;
             client_max_body_size 1000M;
          }
      }
    }


---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: agent
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicas }}
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  serviceName: agent
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      priorityClassName: cykube-high-priority
      serviceAccountName: cykube
{{/*      securityContext:*/}}
{{/*        runAsUser: 10000*/}}
{{/*        runAsGroup: 10000*/}}
{{/*        fsGroup: 10000*/}}
      containers:
        - name: server
          image: "europe-west2-docker.pkg.dev/cykubeapp/cykube/agent:{{ .Values.tag }}"
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 150m
              memory: 200Mi
            limits:
              cpu: 150m
              memory: 200Mi
          livenessProbe:
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 20
            httpGet:
              port: 8101
              path: "/api/hc"
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "cykube-redis"
                  key: "redis-password"
            - name: CACHE_DIR
              value: "/cache"
          envFrom:
            - configMapRef:
                name: cykube-agent-configmap
            - secretRef:
                name: cykube-agent-secrets
          volumeMounts:
          - name: cache
            mountPath: /cache
          ports:
            - containerPort: 8101
              name: agent
              protocol: TCP
        - name: nginx
          image: nginx
          ports:
          - containerPort: 8100
          resources:
            requests:
              cpu: 150m
              memory: 200Mi
            limits:
              cpu: 150m
              memory: 200Mi
          volumeMounts:
          - name: agent-nginx-conf
            mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf
            readOnly: true
  volumeClaimTemplates:
  - metadata:
      name: cache
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ .Values.cache.storageClass }}
      resources:
        requests:
          storage: {{ .Values.cache.size }}

