apiVersion: apps/v1
kind: Deployment
metadata:
  name: cykube-agent
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app: cykube-agent
  template:
    metadata:
      labels:
        app: cykube-agent
    spec:
      priorityClassName: cykube-high-priority
      serviceAccountName: cykube
      containers:
        - name: server
          image: "nickbrookck/cykube-agent:{{ .Values.tag }}"
          imagePullPolicy: IfNotPresent
          args: ["agent"]
          resources:
            requests:
              cpu: 200m
              memory: 200Mi
            limits:
              cpu: 200m
              memory: 200Mi
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "cykube-redis"
                  key: "redis-password"
          envFrom:
            - configMapRef:
                name: cykube-agent-configmap
            - secretRef:
                name: cykube-agent-secrets
          ports:
            - containerPort: 5000
              name: cykube-agent
              protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: cykube-agent
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: cykube-agent
  selector:
    app: cykube-agent
