apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: agent
  namespace: {{ .Release.Namespace }}
spec:
{{- if eq .Values.architecture "replicated" }}
  replicas: {{ .Values.replicas }}
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
{{ else }}
  replicas: 1
{{- end }}
  serviceName: agent
  selector:
    matchLabels:
      app: agent
  template:
    metadata:
      labels:
        app: agent
    spec:
      priorityClassName: "{{ .Release.Namespace }}-high-priority"
      serviceAccountName: cykubed
      securityContext:
        runAsUser: 10000
        runAsGroup: 10000
        fsGroup: 10000
      containers:
        - name: agent
          image: "us-docker.pkg.dev/cykubed/public/agent:{{ .Chart.Version }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          resources:
            requests:
              cpu: 150m
              memory: 200Mi
            limits:
              cpu: 150m
              memory: 200Mi
          envFrom:
            - configMapRef:
                name: cykubed-agent-configmap
            - secretRef:
                name: cykubed-agent-secrets


