apiVersion: v1
kind: Secret
metadata:
  name: cykubed-agent-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  API_TOKEN: {{ required "Please specify the token" .Values.token | b64enc }}
{{ if .Values.sentryDsn }}
  SENTRY_DSN: {{ .Values.sentryDsn | b64enc }}
{{ end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name: cykubed-agent-configmap
data:
  AGENT_VERSION: "{{ .Chart.Version }}"
  MAIN_API_URL: {{ .Values.apiUrl }}
  NAMESPACE: {{ .Release.Namespace }}
  PLATFORM: {{ required "Please specify the target platform" .Values.platform | lower }}
  STORAGE_CLASS: "{{ default .Release.Name .Values.storageClass }}"
  PRIORITY_CLASS: "{{ .Release.Namespace }}-high-priority"
  APP_DISTRIBUTION_CACHE_TTL: "{{ .Values.cache.appTTL }}"
  NODE_DISTRIBUTION_CACHE_TTL: "{{ .Values.cache.nodeTTL }}"
{{ if has .Values.platform .Values.volumeSnapshotClassPlatforms }}
  VOLUME_SNAPSHOT_CLASS: "{{ .Release.Name }}"
{{ end }}
  CYPRESS_RUN_TIMEOUT: "3600"
  REDIS_SECRET_NAME: "{{ .Release.Name }}-redis"
{{ if or (eq .Values.redis.architecture "standalone") (eq .Values.architecture "standalone") }}
  REDIS_HOST: "{{ .Release.Name }}-redis-master.{{ .Release.Namespace }}.svc.cluster.local"
  REDIS_NODES: "1"
{{ else }}
  REDIS_NODES: "{{ .Values.redis.replica.replicaCount }}"
  REDIS_SENTINEL_PREFIX: "{{ .Release.Name }}-redis-headless"
{{ end }}
