apiVersion: v1
kind: Secret
metadata:
  name: cykube-agent-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  API_TOKEN: {{ .Values.token | b64enc }}
  SENTRY_DSN: {{ .Values.sentryDsn | b64enc }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name: cykube-agent-configmap
data:
  AGENT_URL: {{ .Values.agentUrl }}
  MAIN_API_URL: {{ .Values.apiUrl }}
  AGENT_NAME: {{ .Values.agentName }}
  NAMESPACE: {{ .Values.namespace }}
  FILESTORE_SERVERS: "fs-0.agent:8100,fs-1.agent:8100"
  FILESTORE_TOTAL_TIMEOUT: "600"
  FILESTORE_CONNECT_TIMEOUT: "10"
  FILESTORE_READ_TIMEOUT: "300"
  FILESTORE_DISK_SIZE_GB: "10.0"
  FILESTORE_MIN_WRITE: "1"
