apiVersion: v1
kind: Secret
metadata:
  name: cykubed-agent-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  API_TOKEN: {{ required "Please specify the token" .Values.token | b64enc }}
{{ if .Values.sentryDsn }}
  SENTRY_DSN: {{ .Values.sentryDsn | b64enc }}
{{ end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name: cykubed-agent-configmap
data:
  MAIN_API_URL: {{ .Values.apiUrl }}
  NAMESPACE: {{ .Values.namespace }}
  PLATFORM: {{ required "Please specify the target platform" .Values.platform }}
  STORAGE_CLASS: cykubed-storageclass
  CYPRESS_RUN_TIMEOUT: "3600"
  REDIS_SECRET_NAME: "{{ .Release.Name }}-redis"
{{ if or (eq .Values.redis.architecture "standalone") (eq .Values.architecture "standalone") }}
  REDIS_HOST: "{{ .Release.Name }}-redis-master.cykubed.svc.cluster.local"
  REDIS_NODES: "1"
{{ else }}
  REDIS_NODES: "{{ .Values.redis.replica.replicaCount }}"
  REDIS_SENTINEL_PREFIX: "{{ .Release.Name }}-redis-headless"
{{ end }}
