apiVersion: v1
kind: Secret
metadata:
  name: cykubed-agent-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  API_TOKEN: {{ required "Please specify the token" .Values.token | b64enc }}
{{ if .Values.sentryDsn }}
  SENTRY_DSN: {{ .Values.sentryDsn | b64enc }}
{{ end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name: cykubed-agent-configmap
data:
  AGENT_VERSION: "{{ .Chart.Version }}"
  MAIN_API_URL: {{ .Values.apiUrl }}
  NAMESPACE: {{ .Release.Namespace }}
{{- if eq .Values.platform "AKS" }}
  READ_ONLY_MANY: "false"
{{ else }}
  READ_ONLY_MANY: "{{ .Values.readOnlyMany }}"
{{ end }}
  PLATFORM: {{ required "Please specify the target platform" .Values.platform | lower }}
  STORAGE_CLASS: "{{ default .Release.Name .Values.storageClass }}"
  PRIORITY_CLASS: "{{ .Release.Namespace }}-high-priority"
  APP_DISTRIBUTION_CACHE_TTL: "{{ .Values.cache.appTTL }}"
  NODE_DISTRIBUTION_CACHE_TTL: "{{ .Values.cache.nodeTTL }}"
{{ if .Values.keepAliveOnFailure }}
  KEEPALIVE_ON_FAILURE: "true"
{{ end }}
{{ if has .Values.platform .Values.volumeSnapshotClassPlatforms }}
  VOLUME_SNAPSHOT_CLASS: "{{ .Release.Name }}"
{{ end }}
  CYPRESS_RUN_TIMEOUT: "3600"
