apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cykube-agent-mongo-pvc
  namespace: cykube
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20G
---

apiVersion: v1
kind: Service
metadata:
  name: cykube-agent-mongo
  namespace: cykube
spec:
  clusterIP: None
  ports:
  - port: 27017
  selector:
    app: cykube-agent-mongo

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cykube-agent-mongo
  namespace: cykube
spec:
  selector:
    matchLabels:
      app: cykube-agent-mongo
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cykube-agent-mongo
    spec:
      priorityClassName: cykube-high-priority
      terminationGracePeriodSeconds: 10
      containers:
        - name: cykube-agent-mongo
          image: mongo:4.2.23
          resources:
            limits:
              cpu: 500m
              memory: 1G
          ports:
            - containerPort: 27017
          livenessProbe:
            exec:
              command:
              - mongo
              - --eval
              - "db.adminCommand('ping')"
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
              - mongo
              - --eval
              - "db.adminCommand('ping')"
            initialDelaySeconds: 30
            periodSeconds: 10
          volumeMounts:
            - name: mongo-storage
              mountPath: /data/db
      volumes:
      - name: mongo-storage
        persistentVolumeClaim:
          claimName: cykube-agent-mongo-pvc
