apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: "{{ .Release.Namespace }}-high-priority"
value: 1000
globalDefault: false
description: "Ensure that the cykubed agent is not preempted by runner pods"
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: "{{ .Release.Namespace }}-default-priority"
value: 0
globalDefault: false
description: "Ensure that the cykubed runners are lower priority than the agent"
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: "{{ .Release.Namespace }}-lowest-priority"
value: -10
globalDefault: false
description: "Use to preprovision"

