apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: cykube-high-priority
value: 10
globalDefault: false
description: "Ensure that the cykube agent is not preempted by runner pods"
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: cykube-low-priority
value: 0
globalDefault: false
description: "Ensure that the cykube runners are lower priority than the agent"
