apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: cykubed-high-priority
value: 1000
globalDefault: false
description: "Ensure that the cykube agent is not preempted by runner pods"
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: cykubed-low-priority
value: 0
globalDefault: false
description: "Ensure that the cykube runners are lower priority than the agent"
