apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Values.namespace }}
  name: batch-api-role
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "create", "delete"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cykube-binding
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ .Values.namespace }}
roleRef:
  kind: Role
  name: batch-api-role
  apiGroup: ""
