apiVersion: v1
kind: ServiceAccount
metadata:
  {{ if .Values.gcpServiceAccount }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.gcpServiceAccount }}
  {{ end }}
  name: cykubed
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Release.Namespace }}
  name: batch-api-role
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "create", "delete", "watch"]
- apiGroups: ["batch"]
  resources: ["jobs/status"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: [ "pods" ]
  verbs: [ "get", "list", "delete", "watch" ]
- apiGroups: [""]
  resources: [ "persistentvolumeclaims"]
  verbs: [ "create",  "get", "delete", "list", "watch" ]
- apiGroups: ["volumesnapshot.external-storage.k8s.io", "snapshot.storage.k8s.io"]
  resources: ["volumesnapshots"]
  verbs: ["create", "delete", "get", "list", "watch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cykubed-binding
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: cykubed
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: batch-api-role
  apiGroup: ""
