apiVersion: v1
kind: ServiceAccount
metadata:
  name: cykube
  namespace: cykube
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Values.namespace }}
  name: batch-api-role
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "create", "delete"]
- apiGroups: [""]
  resources: [ "pods" ]
  verbs: [ "get", "list", "delete" ]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cykube-binding
  namespace: {{ .Values.namespace }}
subjects:
- kind: ServiceAccount
  name: cykube
  namespace: {{ .Values.namespace }}
roleRef:
  kind: Role
  name: batch-api-role
  apiGroup: ""
