apiVersion: v1
kind: Secret
metadata:
  name: cykube-agent-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  API_TOKEN: {{ .Values.token | b64enc }}
  SENTRY_DSN: {{ .Values.sentryDsn | b64enc }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name: cykube-agent-configmap
data:
  MONGO_HOST: "cykube-mongodb-0.cykube-mongodb-headless.cykube.svc.cluster.local,cykube-mongodb-1.cykube-mongodb-headless.cykube.svc.cluster.local"
  AGENT_URL: {{ .Values.agentUrl }}
  MAIN_API_URL: {{ .Values.apiUrl }}
  AGENT_NAME: {{ .Values.agentName }}
  NAMESPACE: {{ .Values.namespace }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cykube-agent
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: cykube-agent
  template:
    metadata:
      labels:
        app: cykube-agent
    spec:
      priorityClassName: cykube-high-priority
      serviceAccountName: cykube
      containers:
        - name: server
          image: "nickbrookck/cykube-agent:{{ .Values.tag }}"
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 250m
              memory: 0.5G
            limits:
              cpu: 250m
              memory: 0.5G
          env:
            - name: MONGO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "cykube-mongodb"
                  key: "mongodb-root-password"
          envFrom:
            - configMapRef:
                name: cykube-agent-configmap
            - secretRef:
                name: cykube-agent-secrets
          ports:
            - containerPort: 5000
              name: cykube-agent
              protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: cykube-agent
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: cykube-agent
  selector:
    app: cykube-agent
