apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cykube-cache
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.cacheStorage }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-{{ .Values.agentVersion }}-configmap
data:
  API_TOKEN: {{ .Values.token }}
  CACHE_URL: "http://cache"
  AGENT_URL: "http://cykube:5000"
  MAIN_API_URL: {{ .Values.apiUrl }}
  CACHE_DIR: "/var/lib/cykubecache"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: {{ .Release.Namespace }}
data:
  nginx.conf: |
    worker_processes  1;
    events {
        worker_connections  1024;
    }
    http {
      server {
          access_log /var/log/nginx/access.log;
          error_log /var/log/nginx/error.log;
          listen       80;
          server_name  localhost;
          location / {
            root   /var/lib/cykubecache;
            client_max_body_size 200M;
        }
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cykube-server
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: cykube-server
  template:
    metadata:
      labels:
        app: cykube-server
    spec:
      containers:
        - name: server
          image: "{{ .Values.agentImage }}"
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 250m
              memory: 0.5G
            limits:
              cpu: 250m
              memory: 0.5G
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-{{ .Values.agentVersion }}-configmap
          ports:
            - containerPort: 5000
              name: cykube-server
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /hc
              port: cykube-server
          volumeMounts:
            - name: cykube-cache
              mountPath: /var/lib/cykubecache

        - name: nginx
          image: nginx
          resources:
            requests:
              cpu: 250m
              memory: 0.5G
            limits:
              cpu: 250m
              memory: 0.5G
          ports:
          - containerPort: 80
            name: nginx-port
          volumeMounts:
          - name: nginx-conf
            mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf
          - name: cykube-cache
            mountPath: /var/lib/cykubecache

      volumes:
        - name: cykube-cache
          persistentVolumeClaim:
            claimName: cykube-cache
        - name: nginx-conf
          configMap:
            name: nginx-conf
---
apiVersion: v1
kind: Service
metadata:
  name: cykube
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: cykube-server
  selector:
    app: cykube-server
---
apiVersion: v1
kind: Service
metadata:
  name: cache
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: nginx-port
  selector:
    app: cykube-server
