apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cykube-agent-cache
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.cacheStorage }}
---
apiVersion: v1
kind: Secret
metadata:
  name: cykube-agent-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  API_TOKEN: {{ .Values.token | b64enc }}
  SENTRY_DSN: {{ .Values.sentryDsn | b64enc }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name: cykube-agent-configmap
data:
  CACHE_URL: {{ .Values.cacheUrl }}
  AGENT_URL: {{ .Values.agentUrl }}
  MAIN_API_URL: {{ .Values.apiUrl }}
  MONGO_URL: "mongodb://cykube-agent-mongo:27017"
  AGENT_NAME: {{ .Values.agentName }}
  NAMESPACE: {{ .Values.namespace }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: {{ .Release.Namespace }}
data:
  nginx.conf: |
    worker_processes  1;
    events {
        worker_connections  1024;
    }
    http {
      server {
          access_log /var/log/nginx/access.log;
          error_log /var/log/nginx/error.log;
          listen       80;
          server_name  localhost;
          location / {
            root   /var/lib/cykubecache;
            client_max_body_size 200M;
        }
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cykube-agent
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: cykube-agent
  template:
    metadata:
      labels:
        app: cykube-agent
    spec:
      serviceAccountName: cykube
      containers:
        - name: server
          image: "nickbrookck/cykube-agent:{{ .Values.tag }}"
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 250m
              memory: 0.5G
            limits:
              cpu: 250m
              memory: 0.5G
          envFrom:
            - configMapRef:
                name: cykube-agent-configmap
            - secretRef:
                name: cykube-agent-secrets
          ports:
            - containerPort: 5000
              name: cykube-agent
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /hc
              port: cykube-agent
          volumeMounts:
            - name: cykube-cache
              mountPath: /var/lib/cykubecache

        - name: nginx
          image: nginx
          resources:
            requests:
              cpu: 250m
              memory: 0.5G
            limits:
              cpu: 250m
              memory: 0.5G
          ports:
          - containerPort: 80
            name: nginx-port
          volumeMounts:
          - name: nginx-conf
            mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf
          - name: cykube-cache
            mountPath: /var/lib/cykubecache

      volumes:
        - name: cykube-cache
          persistentVolumeClaim:
            claimName: cykube-agent-cache
        - name: nginx-conf
          configMap:
            name: nginx-conf
---
apiVersion: v1
kind: Service
metadata:
  name: cykube-agent
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: cykube-agent
  selector:
    app: cykube-agent
---
apiVersion: v1
kind: Service
metadata:
  name: cykube-cache
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: nginx-port
  selector:
    app: cykube-agent
