apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cykube-persistent-storage
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.cacheStorage }}
