{{- if eq .Values.platform "GKE" }}
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: {{ .Release.Name }}
driver: pd.csi.storage.gke.io
deletionPolicy: Delete

{{- else if eq .Values.platform "AKS" }}
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: {{ .Release.Name }}
driver: disk.csi.azure.com
deletionPolicy: Delete
parameters:
  incremental: "true"

{{- else if eq .Values.platform "minikube" }}
apiVersion: snapshot.storage.k8s.io/v1
deletionPolicy: Delete
driver: hostpath.csi.k8s.io
kind: VolumeSnapshotClass
metadata:
  labels:
    addonmanager.kubernetes.io/mode: EnsureExists
  name: {{ .Release.Name }}

{{- end }}
