apiVersion: batch/v1
kind: Job
metadata:
  generateName: spottest-
  namespace: cykubed
spec:
  backoffLimit: 0
  parallelism: 11
  ttlSecondsAfterFinished: 3600
  template:
    spec:
      restartPolicy: Never
      securityContext:
        runAsNonRoot: true
        fsGroup: 10000
        runAsUser: 10000
        runAsGroup: 10000
      serviceAccountName: "cykubed"
      containers:
        - name: test
          imagePullPolicy: IfNotPresent
          image: europe-docker.pkg.dev/cykubed/public/node-16:3.19.5
          command: [ "/bin/bash", "-c", "--" ]
          args:
             - "sleep 300"

