#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: test-pvc
#  namespace: cykubed
#spec:
#  storageClassName: "cykubed"
#  accessModes:
#    - ReadWriteOnce
#  dataSource:
#    apiGroup: snapshot.storage.k8s.io
#    kind: VolumeSnapshot
#    name: "test-snap1"
#  resources:
#    requests:
#      storage: "10Gi"
#
#---

apiVersion: v1
kind: Pod
metadata:
  name: shellsnap
  namespace: cykubed
spec:
  securityContext:
    runAsNonRoot: true
    fsGroup: 10000
    runAsUser: 10000
    runAsGroup: 10000
  volumes:
    - name: build-volume
#      persistentVolumeClaim:
#        claimName: "test-pvc"
      ephemeral:
        volumeClaimTemplate:
          spec:
            dataSource:
              apiGroup: snapshot.storage.k8s.io
              kind: VolumeSnapshot
              name: test-snap1
            storageClassName: "cykubed"
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 10Gi
  containers:
    - name: shell
      imagePullPolicy: IfNotPresent
      image: us-docker.pkg.dev/cykubed/public/node-16:3.19.5
      command: [ "/bin/bash", "-c", "--" ]
      args:
         - "sleep 3000"
      volumeMounts:
      - mountPath: "/build"
        name: build-volume
