apiVersion: v1
kind: Pod
metadata:
  name: shell
  namespace: cykubed
spec:
  containers:
  - image: ubuntu
    command:
      - "sleep"
      - "604800"
    imagePullPolicy: IfNotPresent
    name: ubuntu
  restartPolicy: Always
