#
# Cypress runner job template
#
apiVersion: batch/v1
kind: Job
metadata:
  name: cypress-runner-{SHA}
spec:
  parallelism: {PARALLELISM}
  template:
    metadata:
      labels:
        branch: {BRANCH}
        job: cypress-runner
    spec:
      hostIPC: true
      containers:
      - name: testrunner
        image: nickbrookdocker/cypress-runner:{CYPRESS_RUNNER_VERSION}
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 1000m
            memory: 1G
        env:
          - name: COMMIT_SHA
            value: {SHA}
          - name: HUB_URL
            value: {HUB_URL}
          - name: DIST_URL
            value: {DIST_URL}
      restartPolicy: Never


