"""Initial

Revision ID: 20d0be213192
Revises:
Create Date: 2021-08-23 20:42:29.999861

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '20d0be213192'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repos', sa.String(length=255), nullable=True),
    sa.Column('started', sa.DateTime(), nullable=True),
    sa.Column('finished', sa.DateTime(), nullable=True),
    sa.Column('sha', sa.String(length=64), nullable=True),
    sa.Column('branch', sa.String(length=128), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('commit_summary', sa.String(length=255), nullable=True),
    sa.Column('commit_link', sa.String(length=255), nullable=True),
    sa.Column('pull_request_link', sa.String(length=255), nullable=True),
    sa.Column('avatar', sa.String(length=255), nullable=True),
    sa.Column('author', sa.String(length=64), nullable=True),
    sa.Column('author_slack_id', sa.String(length=255), nullable=True),
    sa.Column('jira_ticket', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spec_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file', sa.String(length=255), nullable=True),
    sa.Column('testrun_id', sa.Integer(), nullable=False),
    sa.Column('started', sa.DateTime(), nullable=True),
    sa.Column('finished', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['testrun_id'], ['test_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spec_file')
    op.drop_table('test_run')
    # ### end Alembic commands ###
