"""Slack ID and commit_link

Revision ID: 3849533f183d
Revises: 6c7180c0f857
Create Date: 2021-08-23 09:06:49.751608

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '3849533f183d'
down_revision = '6c7180c0f857'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_run', sa.Column('author_slack_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_run', 'author_slack_id')
    # ### end Alembic commands ###
