"""Added account table

Revision ID: a1df531b6f90
Revises: c787d7415bc0
Create Date: 2022-02-20 15:03:27.975282

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a1df531b6f90'
down_revision = 'c787d7415bc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_settings',
    sa.Column('platform_id', sa.Enum('BITBUCKET', 'JIRA', 'SLACK', name='platformenum'), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('token', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('platform_id'),
    sa.UniqueConstraint('platform_id')
    )
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('platform', sa.Enum('BITBUCKET', 'JIRA', 'SLACK', name='platformenum'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('settings')
    op.add_column('test_run', sa.Column('project_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'test_run', 'project', ['project_id'], ['id'])
    op.drop_column('test_run', 'repos')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_run', sa.Column('repos', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
    op.drop_constraint(None, 'test_run', type_='foreignkey')
    op.drop_column('test_run', 'project_id')
    op.create_table('settings',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('hub_url', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('bitbucket_url', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32), nullable=True),
    sa.Column('bitbucket_username', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32), nullable=True),
    sa.Column('bitbucket_password', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32), nullable=True),
    sa.Column('slack_token', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('jira_url', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('jira_user', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32), nullable=True),
    sa.Column('jira_token', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('project')
    op.drop_table('platform_settings')
    # ### end Alembic commands ###
