"""initial

Revision ID: c5448f5c24b8
Revises:
Create Date: 2022-02-23 23:04:41.089925

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'c5448f5c24b8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oauth_token',
    sa.Column('platform', sa.Enum('BITBUCKET', 'JIRA', 'SLACK', name='platformenum'), nullable=False),
    sa.Column('access_token', sa.String(length=255), nullable=True),
    sa.Column('refresh_token', sa.String(length=255), nullable=True),
    sa.Column('expiry', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('platform'),
    sa.UniqueConstraint('platform')
    )
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('platform', sa.Enum('BITBUCKET', 'JIRA', 'SLACK', name='platformenum'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('started', sa.DateTime(), nullable=True),
    sa.Column('finished', sa.DateTime(), nullable=True),
    sa.Column('sha', sa.String(length=64), nullable=True),
    sa.Column('branch', sa.String(length=128), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('commit_summary', sa.String(length=255), nullable=True),
    sa.Column('commit_link', sa.String(length=255), nullable=True),
    sa.Column('pull_request_link', sa.String(length=255), nullable=True),
    sa.Column('avatar', sa.String(length=255), nullable=True),
    sa.Column('author', sa.String(length=64), nullable=True),
    sa.Column('author_slack_id', sa.String(length=255), nullable=True),
    sa.Column('jira_ticket', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spec_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file', sa.String(length=255), nullable=True),
    sa.Column('testrun_id', sa.Integer(), nullable=False),
    sa.Column('started', sa.DateTime(), nullable=True),
    sa.Column('finished', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['testrun_id'], ['test_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spec_file')
    op.drop_table('test_run')
    op.drop_table('project')
    op.drop_table('oauth_token')
    # ### end Alembic commands ###
