"""Settings

Revision ID: c787d7415bc0
Revises: 20d0be213192
Create Date: 2022-02-13 15:48:21.056497

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'c787d7415bc0'
down_revision = '20d0be213192'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hub_url', sa.String(length=255), nullable=True),
    sa.Column('bitbucket_url', sa.String(length=32), nullable=True),
    sa.Column('bitbucket_username', sa.String(length=32), nullable=True),
    sa.Column('bitbucket_password', sa.String(length=32), nullable=True),
    sa.Column('slack_token', sa.String(length=255), nullable=True),
    sa.Column('jira_url', sa.String(length=255), nullable=True),
    sa.Column('jira_user', sa.String(length=32), nullable=True),
    sa.Column('jira_token', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settings')
    # ### end Alembic commands ###
