"""oauth2

Revision ID: da2d20136f28
Revises: a1df531b6f90
Create Date: 2022-02-23 17:45:18.790434

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'da2d20136f28'
down_revision = 'a1df531b6f90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oauth_token',
    sa.Column('platform_id', sa.Enum('BITBUCKET', 'JIRA', 'SLACK', name='platformenum'), nullable=False),
    sa.Column('access_token', sa.String(length=255), nullable=True),
    sa.Column('refresh_token', sa.String(length=255), nullable=True),
    sa.Column('expiry', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('platform_id'),
    sa.UniqueConstraint('platform_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('oauth_token')
    # ### end Alembic commands ###
