"""Initial

Revision ID: e6f75a11716e
Revises:
Create Date: 2021-04-11 11:33:10.120003

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'e6f75a11716e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repos', sa.String(length=255), nullable=True),
    sa.Column('started', sa.DateTime(), nullable=True),
    sa.Column('finished', sa.DateTime(), nullable=True),
    sa.Column('sha', sa.String(length=64), nullable=True),
    sa.Column('branch', sa.String(length=128), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('commit_summary', sa.String(length=255), nullable=True),
    sa.Column('commit_link', sa.String(length=255), nullable=True),
    sa.Column('results_url', sa.String(length=255), nullable=True),
    sa.Column('avatar', sa.String(length=255), nullable=True),
    sa.Column('author', sa.String(length=64), nullable=True),
    sa.Column('jira_ticket', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spec_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file', sa.String(length=255), nullable=True),
    sa.Column('testrun_id', sa.Integer(), nullable=False),
    sa.Column('started', sa.DateTime(), nullable=True),
    sa.Column('finished', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['testrun_id'], ['test_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spec_file')
    op.drop_table('test_run')
    # ### end Alembic commands ###
