apiVersion: v1
kind: Pod
metadata:
  name: shell
  namespace: cykube
spec:
  containers:
    - name: shell
      image: nickbrookck/cykube-agent:9b667fb
      command: ["/bin/sleep", "3600"]
      resources:
        requests:
          cpu: "1"
          memory: "256Mi"
      env:
      - name: REDIS_PASSWORD
        valueFrom:
          secretKeyRef:
            name: "redis-redis-cluster"
            key: "redis-password"


