apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-persistent-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50G
---

apiVersion: v1
kind: Service
metadata:
  name: cypresshub-mysql
spec:
  ports:
  - port: 3306
  selector:
    app: cypresshub-mysql
  clusterIP: None
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cypresshub-mysql
spec:
  selector:
    matchLabels:
      app: cypresshub-mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cypresshub-mysql
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - image: mysql:5.7
        name: mysql
        args:
          - --ignore-db-dir=lost+found --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --bind-address=0.0.0.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cypresshub-secrets
              key: MYSQL_PASSWORD
        - name: MYSQL_USER
          value: cypresshub
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cypresshub-secrets
              key: MYSQL_PASSWORD
        - name: MYSQL_DATABASE
          value: cypresshub
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-persistent-storage

