on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: cykubed/cykubed-common/.github/workflows/build.yaml@master
        with:
          tag: "${{ github.ref_name }}"

      - name: 'Build chart'
        uses: 'alpine/helm:3.16'
        with:






