on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      - 'test-+.'
jobs:
  build:
    uses: cykubed/cykubed-common/.github/workflows/build.yaml@master
    secrets: inherit
    with:
      tag: "${{ github.ref_name }}"

  deploy:
    runs-on: 'ubuntu-latest'
    needs: build
    container:
      image: ghcr.io/cykubed/helm-wrangler:1.0
      env:
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        CYKUBED_API_TOKEN: ${{ secrets.CYKUBED_API_TOKEN }}
        SLACK_HOOK_URL: ${{ secrets.SLACK_HOOK_URL }}
    steps:
    - name: 'Build chart'
      run: "./scripts/build.sh ${{ github.ref_name }}"








